apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-cli-run-with-auth
spec:
  taskRef:
    name: git-cli
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: git-source      
    - name: ssh-directory
      secret:
        secretName: my-ssh-credentials
  params:
    - name: GIT_SCRIPT
      value: |
        git init
        git remote add origin https://github.com/daintree-henry/msa-containerapp-java-employeeapi
        git pull origin main