apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: buildah-build-and-push-run-tag
spec:
  taskRef:
    name: buildah-tag
  params:
  - name: IMAGE
    value: docker.io/dainforest/cicd-test
  - name: TAG
    value: :v3
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: git-source 
